# Generated by Django 4.1.13 on 2024-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('description', models.TextField(verbose_name='Feedback Description')),
                ('rating', models.IntegerField(default=5, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
