# Generated by Django 4.1.13 on 2024-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='User Feedback Description')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
