# Generated by Django 4.1.12 on 2024-01-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0007_alter_feedback_description_alter_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
