# Generated by Django 4.1.13 on 2024-02-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignupLogin', '0003_remove_user_last_login_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
