# Generated by Django 4.1.13 on 2024-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('description', models.TextField(verbose_name='Feedback Description')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
