# Generated by Django 4.1.13 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_feedback_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(default='Good', max_length=500),
        ),
    ]
