# Generated by Django 4.1.12 on 2024-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0006_alter_feedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
